export const GET_CATEGORY_REQUESTING = "GET_CATEGORY_REQUESTING";
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAILED = "GET_CATEGORY_FAILED";

export const ADD_CATEGORY_REQUESTING = "ADD_CATEGORY_REQUESTING";
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";
export const ADD_CATEGORY_FAILED = "ADD_CATEGORY_FAILED";

export const REMOVE_CATEGORY_REQUESTING = "REMOVE_CATEGORY_REQUESTING";
export const REMOVE_CATEGORY_SUCCESS = "REMOVE_CATEGORY_SUCCESS";
export const REMOVE_CATEGORY_FAILED = "REMOVE_CATEGORY_FAILED";

export const UPDATE_CATEGORY_REQUESTING = "UPDATE_CATEGORY_REQUESTING";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILED = "UPDATE_CATEGORY_FAILED";


export const GET_COSMETICS_LIST_BY_CATEGORYID = 'GET_COSMETICS_LIST_BY_CATEGORYID';
export const GET_PET_LIST_BY_CATEGORYID = 'GET_PET_LIST_BY_CATEGORYID';
export const GET_PRINT_LIST_BY_CATEGORYID = 'GET_PRINT_LIST_BY_CATEGORYID';
export const GET_BOTTLE_LIST_BY_CATEGORYID = 'GET_BOTTLE_LIST_BY_CATEGORYID';
export const GET_BOX_LIST_BY_CATEGORYID = 'GET_BOX_LIST_BY_CATEGORYID';
