export const ADD_PRODUCT_REQUESTING = "ADD_PRODUCT_REQUESTING";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

export const DELETE_PRODUCT_REQUESTING = "DELETE_PRODUCT_REQUESTING";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

export const GET_PRODUCTS_REQUESTING = "GET_PRODUCTS_REQUESTING";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

export const GET_PRODUCT_DETAIL_REQUESTING = "GET_PRODUCT_DETAIL_REQUESTING";
export const GET_PRODUCT_DETAIL_SUCCESS = "GET_PRODUCT_DETAIL_SUCCESS";
export const GET_PRODUCT_DETAIL_FAILED = "GET_PRODUCT_DETAIL_FAILED";

export const EDIT_PRODUCT_REQUESTING = "EDIT_PRODUCT_REQUESTING";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILED = "EDIT_PRODUCT_FAILED";
