export const LOGIN_REQUESTING = "LOGIN_REQUESTING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT = "LOGOUT";

export const ADD_ORDER_REQUESTING = "ADD_ORDER_REQUESTING";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAILED = "ADD_ORDER_FAILED";

export const GET_ORDERS_REQUESTING = "GET_ORDERS_REQUESTING";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAILED = "GET_ORDERS_FAILED";

export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAILED = "DELETE_ORDER_FAILED";

export const GET_ALL_CUSTOMER_PENDING = 'GET_ALL_CUSTOMER_PENDING'
export const GET_ALL_CUSTOMER_SUCCESS = 'GET_ALL_CUSTOMER_SUCCESS'
export const GET_ALL_CUSTOMER_FAILED = "GET_ALL_CUSTOMER_FAILED"


export const ADD_CUSTOMER_PENDING = 'ADD_CUSTOMER_PENDING'
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS'
export const ADD_CUSTOMER_FAILED = "ADD_CUSTOMER_FAILED"
